spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zbdz?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379

file:
  upload:
    base-path: D:\houtaifile  # 本地存储根目录（Linux示例）
    # base-path: D:/customized_files  # Windows示例
    allowed-types: image/jpeg,image/png,image/gif,application/pdf  # 允许的文件类型
    max-size: 10485760  # 单个文件最大10MB（单位：字节）

#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCLLJT
#    username: ljt
#    password: abc

server:
  port: 9096
  address: 0.0.0.0
  

mybatis:
  configuration:
    map-underscore-to-camel-case: true

app:
  cors:
    allowed-origins:
      - http://localhost:5173
    allowed-origin-patterns: [] # 需要时可填如 http://localhost:*
    allowed-methods:
      - '*'
    allowed-headers:
      - '*'
    allow-credentials: true
    max-age: 3600

